name: Set up NodeJS environment
description: Prepares environment for NodeJS
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 
          'npm'
    - name: Install global dependencies
      shell: bash
      run: |
        npm -g install svgo svg2vectordrawable avocado
