name: Set up NodeJS environment
description: Prepares environment for NodeJS
inputs:
  os:
    description: The runner os
    required: true
runs:
  using: 'composite'
  steps:
    - name: Restore NPM cache
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm/**/*
        key: npm-cache-${{ inputs.os }}
    - shell: bash
      run: touch package-lock.json
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install global dependencies
      shell: bash
      run: |
        npm -g install svgo svg2vectordrawable avocado
