name: CLI Integrity check
description: Runs the CLI command checking if it still works as intended
inputs:
  type:
    description: File type to parse
    required: true
    default: svg
runs:
  using: composite
  steps:
    - name: Verify ${{ inputs.type }} conversion without optimization
      shell: bash
      run: |
        ./.github/actions/cli-integrity-check/script.sh . ${{ inputs.type }}
    - name: Verify ${{ inputs.type }} conversion with optimization
      shell: bash
      run: |
        ./.github/actions/cli-integrity-check/script.sh . ${{ inputs.type }} optimize
