name: CLI Integrity check
description: Runs the CLI command checking if it still works as intended
inputs:
  type:
    description: File type to parse
    required: true
    default: svg
runs:
  using: composite
  steps:
    - name: Verify simple svg conversion without optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/ShieldSolid.${{ inputs.type }}.NonOptimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=false \
              samples/shield-halved-solid.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff --strip-trailing-cr integrity-check/ShieldSolid.${{ inputs.type }}.NonOptimized.kt samples/ShieldSolid.${{ inputs.type }}.nonoptimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify complex svg conversion without optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/Illustration.${{ inputs.type }}.NonOptimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=false \
              samples/illustration.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff --strip-trailing-cr integrity-check/Illustration.${{ inputs.type }}.NonOptimized.kt samples/Illustration.${{ inputs.type }}.nonoptimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify simple svg conversion with optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/ShieldSolid.${{ inputs.type }}.Optimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=true \
              samples/shield-halved-solid.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff --strip-trailing-cr integrity-check/ShieldSolid.${{ inputs.type }}.Optimized.kt samples/ShieldSolid.${{ inputs.type }}.optimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify complex svg conversion with optimization
      shell: bash
      run: |
        ./s2c -o integrity-check/Illustration.${{ inputs.type }}.Optimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=true \
              samples/illustration.svg
    - name: Compare files with diff
      shell: bash
      run: |
        diff --strip-trailing-cr integrity-check/Illustration.${{ inputs.type }}.Optimized.kt samples/Illustration.${{ inputs.type }}.optimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi
