name: CLI Integrity check
description: Runs the CLI command checking if it still works as intended
inputs:
  shell:
    description: Which shell to run the script
    required: true
    default: bash
runs:
  using: composite
  steps:
    - name: Verify simple svg conversion without optimization
      shell: ${{ inputs.shell }}
      run: |
        ./s2c -o integrity-check/ShieldSolid.NonOptimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=false \
              samples/shield-halved-solid.svg
    - name: Compare files with diff
      shell: ${{ inputs.shell }}
      run: |
        diff --strip-trailing-cr integrity-check/ShieldSolid.NonOptimized.kt samples/ShieldSolid.nonoptimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify complex svg conversion without optimization
      shell: ${{ inputs.shell }}
      run: |
        ./s2c -o integrity-check/Illustration.NonOptimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=false \
              samples/illustration.svg
    - name: Compare files with diff
      shell: ${{ inputs.shell }}
      run: |
        diff --strip-trailing-cr integrity-check/Illustration.NonOptimized.kt samples/Illustration.nonoptimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify simple svg conversion with optimization
      shell: ${{ inputs.shell }}
      run: |
        ./s2c -o integrity-check/ShieldSolid.Optimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=true \
              samples/shield-halved-solid.svg
    - name: Compare files with diff
      shell: ${{ inputs.shell }}
      run: |
        diff --strip-trailing-cr integrity-check/ShieldSolid.Optimized.kt samples/ShieldSolid.optimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi

    - name: Verify complex svg conversion with optimization
      shell: ${{ inputs.shell }}
      run: |
        ./s2c -o integrity-check/Illustration.Optimized.kt \
              -p dev.tonholo.composeicons.ui.icon \
              --theme dev.tonholo.composeicons.ui.theme.ComposeIconsTheme \
              -opt=true \
              samples/illustration.svg
    - name: Compare files with diff
      shell: ${{ inputs.shell }}
      run: |
        diff --strip-trailing-cr integrity-check/Illustration.Optimized.kt samples/Illustration.optimized.kt
        if [[ $? -eq 0 ]]; then
          echo "✅ Integrity check pass"
        else
          echo "❌ Integrity check failed"
          exit 1
        fi
