name: Build
on: workflow_call
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Prepares environment for building
        uses: ./.github/actions/setup

      - name: Prepare nodeJS enviroment for integrity check
        uses: ./.github/actions/setup-nodejs
        with:
          os: ${{ matrix.os }}

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ matrix.os }}

      - name: Build Native Binary for macos
        if: matrix.os == 'macos-latest'
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          job-id: ${{ matrix.os }}
          arguments: releaseMacOS

      - name: Build Native Binary for Windows
        if: matrix.os == 'windows-latest'
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          job-id: ${{ matrix.os }}
          arguments: releaseWindows

      - name: Build Native Binary for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          job-id: ${{ matrix.os }}
          arguments: releaseLinux
